Focus trap
Matteo-Grellier/TheseusMaze pull request #17
Opened 2023-05-16 13:59 UTC by Matteo-Grellier

2023-05-18 14:35 UTC, matheoleger requested changes

2023-05-18 14:35 UTC, matheoleger commented on Assets/Scripts/Maze.cs
> +                // Debug.Log("[maze] mazeArray[" + x + "," + y +"] = mazeRoomsArray[" + room + "]roomArray[" + innerX + "," + innerY + "] = " + mazeRoomsArray[room].roomArray[innerX,innerY]);
You change this files ?

2023-05-18 14:46 UTC, Matteo-Grellier commented on Assets/Scripts/Maze.cs
> +                // Debug.Log("[maze] mazeArray[" + x + "," + y +"] = mazeRoomsArray[" + room + "]roomArray[" + innerX + "," + innerY + "] = " + mazeRoomsArray[room].roomArray[innerX,innerY]);
Yes

2023-05-21 17:34 UTC, matheoleger approved these changes

2023-05-21 17:47 UTC, merged